# Generated by Django 4.2.5 on 2023-10-03 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
            ],
            options={
                'db_table': 'experience_detail',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('profile_summary', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
            ],
            options={
                'db_table': 'profile_summary',
            },
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('institute_name', models.CharField(max_length=255)),
                ('joining_year', models.IntegerField()),
                ('passing_year', models.IntegerField()),
                ('institute_state', models.CharField(blank=True, max_length=255, null=True)),
                ('institute_city', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
            ],
            options={
                'db_table': 'profile_education',
            },
        ),
        migrations.CreateModel(
            name='ProfileExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
            ],
            options={
                'db_table': 'profile_experience',
            },
        ),
        migrations.CreateModel(
            name='ProfileProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField()),
                ('project_skills', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
            ],
            options={
                'db_table': 'profile_project',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category_name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
            ],
            options={
                'db_table': 'skill_category',
            },
        ),
        migrations.CreateModel(
            name='ProfileSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('skill_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
                ('skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.skillcategory')),
            ],
            options={
                'db_table': 'profile_skill',
            },
        ),
        migrations.CreateModel(
            name='ExperienceResponsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('datamode', models.CharField(blank=True, choices=[('D', 'Deleted'), ('I', 'Inactive'), ('A', 'Active')], default='A', max_length=12, null=True)),
                ('experience_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.experiencedetail')),
            ],
            options={
                'db_table': 'experience_responsibilities',
            },
        ),
        migrations.AddField(
            model_name='experiencedetail',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profileexperience'),
        ),
    ]
